# Generated by Django 3.1.5 on 2021-01-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Tên liên lạc')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Số điện thoại')),
                ('type', models.IntegerField(default=1, verbose_name='Loại')),
            ],
        ),
    ]
